function whole(){
    return [
    [],
    [
        [
            {"word":"Handlung", "meaning":"行為", "gender":"f"},
            {"word":"Schritt", "meaning":"歩み", "gender":"m"},
            {"word":"Sturz", "meaning":"転倒", "gender":"m"}
        ],
        [
            {"word":"Absicht", "meaning":"意図, 故意", "gender":"f"},
            {"word":"Fehler", "meaning":"間違い", "gender":"m"},
            {"word":"Folge", "meaning":"結果", "gender":"f"},
            {"word":"Gedächtnis", "meaning":"記憶", "gender":"n"},
            {"word":"Gedanke", "meaning":"考え", "gender":"m"},
            {"word":"Geist", "meaning":"精神", "gender":"m"},
            {"word":"Grund", "meaning":"理由", "gender":"m"},
            {"word":"Kenntnis", "meaning":"知識", "gender":"f"},
            {"word":"Lösung", "meaning":"解決", "gender":"f"},
            {"word":"Plan", "meaning":"計画", "gender":"m"},
            {"word":"Ursache", "meaning":"原因", "gender":"f"},
            {"word":"Verabredung", "meaning":"会う約束", "gender":"f"},
            {"word":"Vernunft", "meaning":"理性", "gender":"f"},
            {"word":"Vorsicht", "meaning":"用心", "gender":"f"},
            {"word":"Wille", "meaning":"意志", "gender":"m"},
            {"word":"Zweck", "meaning":"目的", "gender":"m"}
        ],
        [
            {"word":"Ärger", "meaning":"怒り", "gender":"m"},
            {"word":"Blick", "meaning":"まなざし", "gender":"m"},
            {"word":"Elend", "meaning":"悲惨, 困窮", "gender":"n"},
            {"word":"Freude", "meaning":"喜び", "gender":"f"},
            {"word":"Freundschaft", "meaning":"友情", "gender":"f"},
            {"word":"Geruch", "meaning":"匂い", "gender":"m"},
            {"word":"Geschmack", "meaning":"味", "gender":"m"},
            {"word":"Hass", "meaning":"憎悪", "gender":"m"},
            {"word":"Hoffnung", "meaning":"希望", "gender":"f"},
            {"word":"Liebe", "meaning":"愛", "gender":"f"},
            {"word":"Lust", "meaning":"欲望", "gender":"f"},
            {"word":"Schreck", "meaning":"驚き", "gender":"m"},
            {"word":"Sorge", "meaning":"心配", "gender":"f"},
            {"word":"Träne", "meaning":"涙", "gender":"f"},
            {"word":"Unglück", "meaning":"不運", "gender":"n"},
            {"word":"Wut", "meaning":"激怒", "gender":"f"}
        ],
        [
            {"word":"Art", "meaning":"種類", "gender":"f"},
            {"word":"Bedingung", "meaning":"条件", "gender":"f"},
            {"word":"Beziehung", "meaning":"関係", "gender":"f"},
            {"word":"Ereignis", "meaning":"出来事", "gender":"n"},
            {"word":"Ergebnis", "meaning":"結果", "gender":"n"},
            {"word":"Existenz", "meaning":"存在", "gender":"f"},
            {"word":"Gegenteil", "meaning":"反対", "gender":"n"},
            {"word":"Stimmung", "meaning":"雰囲気", "gender":"f"},
            {"word":"Unterschied", "meaning":"違い", "gender":"m"},
            {"word":"Wechsel", "meaning":"交替", "gender":"m"},
            {"word":"Weise", "meaning":"方法", "gender":"f"},
            {"word":"Wirkung", "meaning":"効果", "gender":"f"},
            {"word":"Zufall", "meaning":"偶然", "gender":"m"}

        ]
    ],
    [
        [],
        [
            {"word":"Bad", "meaning":"風呂", "gender":"n"},
            {"word":"Bügel", "meaning":"ハンガー", "gender":"m"},
            {"word":"Dusche", "meaning":"シャワー", "gender":"f"},
            {"word":"Eimer", "meaning":"バケツ", "gender":"m"},
            {"word":"Faden", "meaning":"糸", "gender":"m"},
            {"word":"Kamm", "meaning":"くし", "gender":"m"},
            {"word":"Rasierapparat", "meaning":"ひげそり", "gender":"m"},
            {"word":"Schampun", "meaning":"シャンプー", "gender":"n"},
            {"word":"Schere", "meaning":"はさみ", "gender":"f"},
            {"word":"Seife", "meaning":"石鹸", "gender":"f"},
            {"word":"Spiegel", "meaning":"鏡", "gender":"m"},
            {"word":"Tuch", "meaning":"タオル", "gender":"n"},
            {"word":"Zahnbürste", "meaning":"歯ブラシ", "gender":"f"},
            {"word":"Batterie", "meaning":"電池", "gender":"f"},
            {"word":"Bügeleisen", "meaning":"アイロン", "gender":"n"},
            {"word":"Heizung", "meaning":"暖房", "gender":"f"},
            {"word":"Kalender", "meaning":"カレンダー", "gender":"m"},
            {"word":"Kreditkarte", "meaning":"クレジットカード", "gender":"f"},
            {"word":"Kühlschrank", "meaning":"冷蔵庫", "gender":"m"},
            {"word":"Mülleimer", "meaning":"ごみ箱", "gender":"m"},
            {"word":"Portmonee", "meaning":"財布", "gender":"n"},
            {"word":"Schirm", "meaning":"傘", "gender":"m"},
            {"word":"Schlüssel", "meaning":"鍵", "gender":"m"},
            {"word":"Staubsauger", "meaning":"掃除機", "gender":"m"},
            {"word":"Uhr", "meaning":"時計", "gender":"f"},
            {"word":"Waschmaschine", "meaning":"洗濯機", "gender":"f"},
            {"word":"Waschmittel", "meaning":"洗剤", "gender":"n"},
            {"word":"Zigarette", "meaning":"たばこ", "gender":"f"},
            {"word":"Bedienung", "meaning":"給仕", "gender":"f"},
            {"word":"Gerät", "meaning":"道具", "gender":"n"},
            {"word":"Geschäft", "meaning":"商店", "gender":"n"},
            {"word":"Kasse", "meaning":"レジ", "gender":"f"},
            {"word":"Konto", "meaning":"口座", "gender":"n"},
            {"word":"Kunde", "meaning":"顧客", "gender":"m"},
            {"word":"Preis", "meaning":"値段", "gender":"m"},
            {"word":"Rechnung", "meaning":"勘定(書)", "gender":"f"},
            {"word":"Tätigkeit", "meaning":"活動, 作業", "gender":"f"},
            {"word":"Ware", "meaning":"品物", "gender":"f"},
            {"word":"Wäscherei", "meaning":"クリーニング", "gender":"f"}
        ],
        [
            {"word":"Dose", "meaning":"缶", "gender":"f"},
            {"word":"Flasche", "meaning":"瓶", "gender":"f"},
            {"word":"Gabel", "meaning":"フォーク", "gender":"f"},
            {"word":"Glas", "meaning":"グラス", "gender":"n"},
            {"word":"Löffel", "meaning":"スプーン", "gender":"m"},
            {"word":"Messer", "meaning":"ナイフ", "gender":"n"},
            {"word":"Pfeffer", "meaning":"胡椒", "gender":"m"},
            {"word":"Salz", "meaning":"塩", "gender":"n"},
            {"word":"Senf", "meaning":"からし", "gender":"m"},
            {"word":"Soße", "meaning":"ソース", "gender":"f"},
            {"word":"Stäbchen", "meaning":"箸", "gender":"n"},
            {"word":"Teller", "meaning":"皿", "gender":"m"},
            {"word":"Zucker", "meaning":"砂糖", "gender":"m"},
            {"word":"Apfel", "meaning":"リンゴ", "gender":"m"},
            {"word":"Banane", "meaning":"バナナ", "gender":"f"},
            {"word":"Birne", "meaning":"梨", "gender":"f"},
            {"word":"Erdbeere", "meaning":"イチゴ", "gender":"f"},
            {"word":"Orange", "meaning":"オレンジ", "gender":"f"},
            {"word":"Traube", "meaning":"ブドウ", "gender":"f"},
            {"word":"Zitrone", "meaning":"レモン", "gender":"f"},
            {"word":"Aubergine", "meaning":"ナス", "gender":"f"},
            {"word":"Bohne", "meaning":"豆", "gender":"f"},
            {"word":"Kartoffel", "meaning":"ジャガイモ", "gender":"f"},
            {"word":"Knoblauch", "meaning":"ニンニク", "gender":"m"},
            {"word":"Kohl", "meaning":"キャベツ", "gender":"m"},
            {"word":"Möhre", "meaning":"ニンジン", "gender":"f"},
            {"word":"Spinat", "meaning":"ほうれん草", "gender":"m"},
            {"word":"Zwiebel", "meaning":"玉ねぎ", "gender":"f"},
            {"word":"Bier", "meaning":"ビール", "gender":"n"},
            {"word":"Brot", "meaning":"パン", "gender":"n"},
            {"word":"Butter", "meaning":"バター", "gender":"f"},
            {"word":"Ei", "meaning":"卵", "gender":"n"},
            {"word":"Fleischgericht", "meaning":"肉料理", "gender":"n"},
            {"word":"Kaffe", "meaning":"コーヒー", "gender":"m"},
            {"word":"Käse", "meaning":"チーズ", "gender":"m"},
            {"word":"Kuchen", "meaning":"ケーキ", "gender":"m"},
            {"word":"Pommes frites", "meaning":"フライドポテト", "gender":"p"},
            {"word":"Salat", "meaning":"サラダ", "gender":"m"},
            {"word":"Schokolade", "meaning":"チョコレート", "gender":"f"},
            {"word":"Steak", "meaning":"ステーキ", "gender":"n"},
            {"word":"Suppe", "meaning":"スープ", "gender":"f"},
            {"word":"Wein", "meaning":"ワイン", "gender":"m"},
            {"word":"Wurst", "meaning":"ソーセージ", "gender":"f"},
            {"word":"Durst", "meaning":"渇き", "gender":"m"},
            {"word":"Eis", "meaning":"アイスクリーム", "gender":"n"},
            {"word":"Frühstück", "meaning":"朝食", "gender":"n"},
            {"word":"Gemüse", "meaning":"野菜", "gender":"n"},
            {"word":"Gericht", "meaning":"料理", "gender":"n"},
            {"word":"Geschirr", "meaning":"食器類", "gender":"n"},
            {"word":"Hunger", "meaning":"空腹", "gender":"m"},
            {"word":"Imbiss", "meaning":"軽食", "gender":"m"},
            {"word":"Lebensmittel", "meaning":"食料品", "gender":"n"},
            {"word":"Milch", "meaning":"牛乳", "gender":"f"},
            {"word":"Öl", "meaning":"油", "gender":"n"},
            {"word":"Portion", "meaning":"[飲食物の] 1人前", "gender":"f"},
            {"word":"Reis", "meaning":"米", "gender":"m"},
            {"word":"Saft", "meaning":"ジュース", "gender":"m"},
            {"word":"Sahne", "meaning":"生クリーム", "gender":"f"},
            {"word":"Speisekarte", "meaning":"メニュー", "gender":"f"},
            {"word":"Wasser", "meaning":"水", "gender":"n"}
        ],
        [
            {"word":"Anzug", "meaning":"スーツ", "gender":"m"},
            {"word":"Bluse", "meaning":"ブラウス", "gender":"f"},
            {"word":"Hemd", "meaning":"シャツ", "gender":"n"},
            {"word":"Hose", "meaning":"ズボン", "gender":"f"},
            {"word":"Jacke", "meaning":"ジャケット", "gender":"f"},
            {"word":"Jeans", "meaning":"ジーンズ", "gender":"f"},
            {"word":"Kleid", "meaning":"ドレス, ワンピース", "gender":"n"},
            {"word":"Krawatte", "meaning":"ネクタイ", "gender":"f"},
            {"word":"Mantel", "meaning":"コート", "gender":"m"},
            {"word":"Pullover", "meaning":"セーター", "gender":"m"},
            {"word":"Regenmantel", "meaning":"レインコート", "gender":"m"},
            {"word":"Schlafanzug", "meaning":"パジャマ", "gender":"m"},
            {"word":"Schuh", "meaning":"靴", "gender":"m"},
            {"word":"Armbanduhr", "meaning":"腕時計", "gender":"f"},
            {"word":"Brille", "meaning":"眼鏡", "gender":"f"},
            {"word":"Diamant", "meaning":"ダイヤモンド", "gender":"m"},
            {"word":"Grütel", "meaning":"ベルト", "gender":"m"},
            {"word":"Halskette", "meaning":"ネックレス", "gender":"f"},
            {"word":"Handschuh", "meaning":"手袋", "gender":"m"},
            {"word":"Handtasche", "meaning":"ハンドバッグ", "gender":"f"},
            {"word":"Handtuch", "meaning":"ハンカチ", "gender":"n"},
            {"word":"Hut", "meaning":"帽子", "gender":"m"},
            {"word":"Lippenstift", "meaning":"口紅", "gender":"m"},
            {"word":"Ring", "meaning":"指輪", "gender":"m"},
            {"word":"Rock", "meaning":"スカート", "gender":"m"},
            {"word":"Schal", "meaning":"マフラー", "gender":"m"},
            {"word":"Sonnenbrille", "meaning":"サングラス", "gender":"f"},
            {"word":"Strumpf", "meaning":"ストッキング", "gender":"m"},
            {"word":"Ärmel", "meaning":"袖", "gender":"m"},
            {"word":"Halstuch", "meaning":"スカーフ", "gender":"n"},
            {"word":"Kleidung", "meaning":"[総称として] 服", "gender":"f"},
            {"word":"Mode", "meaning":"流行", "gender":"f"},
            {"word":"Schmuck", "meaning":"アクセサリー", "gender":"m"},
            {"word":"Unterwäsche", "meaning":"下着", "gender":"f"}
        ],
        [
            {"word":"Bett", "meaning":"ベッド", "gender":"n"},
            {"word":"Bücherregal", "meaning":"本棚", "gender":"n"},
            {"word":"Decke", "meaning":"天井", "gender":"f"},
            {"word":"Fenster", "meaning":"窓", "gender":"n"},
            {"word":"Fußboden", "meaning":"床", "gender":"m"},
            {"word":"Kopfkissen", "meaning":"枕", "gender":"n"},
            {"word":"Lampe", "meaning":"ランプ", "gender":"f"},
            {"word":"Sofa", "meaning":"ソファー", "gender":"n"},
            {"word":"Steckdose", "meaning":"コンセント", "gender":"f"},
            {"word":"Stuhl", "meaning":"椅子", "gender":"m"},
            {"word":"Tisch", "meaning":"机", "gender":"m"},
            {"word":"Tür", "meaning":"ドア", "gender":"f"},
            {"word":"Wand", "meaning":"壁", "gender":"f"},
            {"word":"Arbeitszimmer", "meaning":"書斎", "gender":"n"},
            {"word":"Dach", "meaning":"屋根", "gender":"n"},
            {"word":"Eingang", "meaning":"玄関", "gender":"m"},
            {"word":"Empfangszimmer", "meaning":"応接間", "gender":"n"},
            {"word":"Esszimmer", "meaning":"食堂", "gender":"n"},
            {"word":"Flur", "meaning":"廊下", "gender":"m"},
            {"word":"Garage", "meaning":"ガレージ", "gender":"f"},
            {"word":"Gartem", "meaning":"庭", "gender":"m"},
            {"word":"Keller", "meaning":"地下室", "gender":"m"},
            {"word":"Küche", "meaning":"キッチン", "gender":"f"},
            {"word":"Rolltreppe", "meaning":"エスカレーター", "gender":"f"},
            {"word":"Schlafzimmer", "meaning":"寝室", "gender":"n"},
            {"word":"Toilette", "meaning":"トイレ", "gender":"f"},
            {"word":"Treppe", "meaning":"階段", "gender":"f"},
            {"word":"Wohnzimmer", "meaning":"居間", "gender":"n"},
            {"word":"Appartement", "meaning":"アパート", "gender":"n"},
            {"word":"Gas", "meaning":"ガス", "gender":"n"},
            {"word":"Bau", "meaning":"[一般的に] 建物", "gender":"m"},
            {"word":"Gebäude", "meaning":"[公共の] 建物", "gender":"n"},
            {"word":"Haus", "meaning":"家", "gender":"n"},
            {"word":"Haushalt", "meaning":"所帯", "gender":"m"},
            {"word":"Hochhaus", "meaning":"高層ビル", "gender":"n"},
            {"word":"Miete", "meaning":"家賃", "gender":"f"},
            {"word":"Mieter", "meaning":"賃貸人", "gender":"m"},
            {"word":"Möbel", "meaning":"家具", "gender":"n"},
            {"word":"Pantoffel", "meaning":"スリッパ", "gender":"m"},
            {"word":"Stock", "meaning":"階", "gender":"m"},
            {"word":"Strom", "meaning":"電気", "gender":"m"},
            {"word":"Vorhang", "meaning":"カーテン", "gender":"m"},
            {"word":"Wasserleitung", "meaning":"水道", "gender":"f"},
            {"word":"Zimmer", "meaning":"部屋", "gender":"n"}
        ],
        [
            {"word":"Bruder", "meaning":"兄弟", "gender":"m"},
            {"word":"Ehepaar", "meaning":"夫婦", "gender":"n"},
            {"word":"Eltern", "meaning":"両親", "gender":"p"},
            {"word":"Enkel", "meaning":"孫", "gender":"m"},
            {"word":"Großeltern", "meaning":"祖父母", "gender":"p"},
            {"word":"Kind", "meaning":"子ども", "gender":"n"},
            {"word":"Mutter", "meaning":"母", "gender":"f"},
            {"word":"Onkel", "meaning":"おじ", "gender":"m"},
            {"word":"Schwester", "meaning":"姉妹", "gender":"f"},
            {"word":"Sohn", "meaning":"息子", "gender":"m"},
            {"word":"Tante", "meaning":"おば", "gender":"f"},
            {"word":"Tochter", "meaning":"娘", "gender":"f"},
            {"word":"Vater", "meaning":"父", "gender":"m"},
            {"word":"Alte", "meaning":"老人", "gender":"m"},
            {"word":"Alter", "meaning":"年齢", "gender":"n"},
            {"word":"Baby", "meaning":"赤ん坊", "gender":"n"},
            {"word":"Charakter", "meaning":"性格", "gender":"m"},
            {"word":"Erwachsene", "meaning":"大人", "gender":"m"},
            {"word":"Freund", "meaning":"友", "gender":"m"},
            {"word":"Gast", "meaning":"来客", "gender":"m"},
            {"word":"Geschlecht", "meaning":"性(別)", "gender":"n"},
            {"word":"Name", "meaning":"名前", "gender":"m"},
            {"word":"Party", "meaning":"パーティー", "gender":"f"}

        ],
        [
            {"word":"Kopf", "meaning":"頭", "gender":"m"},
            {"word":"Haar", "meaning":"髪", "gender":"n"},
            {"word":"Gesicht", "meaning":"顔", "gender":"n"},
            {"word":"Auge", "meaning":"目", "gender":"n"},
            {"word":"Nase", "meaning":"鼻", "gender":"f"},
            {"word":"Backe", "meaning":"頬", "gender":"f"},
            {"word":"Ohr", "meaning":"耳", "gender":"n"},
            {"word":"Mund", "meaning":"口", "gender":"m"},
            {"word":"Bart", "meaning":"ひげ", "gender":"m"},
            {"word":"Lippe", "meaning":"唇", "gender":"f"},
            {"word":"Zahn", "meaning":"歯", "gender":"m"},
            {"word":"Zunge", "meaning":"舌", "gender":"f"},
            {"word":"Kehle", "meaning":"喉", "gender":"f"},
            {"word":"Hals", "meaning":"首", "gender":"m"},
            {"word":"Schulter", "meaning":"肩", "gender":"f"},
            {"word":"Brust", "meaning":"胸", "gender":"f"},
            {"word":"Bauch", "meaning":"腹", "gender":"m"},
            {"word":"Rücken", "meaning":"背中", "gender":"m"},
            {"word":"Hüfte", "meaning":"腰", "gender":"f"},
            {"word":"Gesäß", "meaning":"尻", "gender":"n"},
            {"word":"Arm", "meaning":"腕", "gender":"m"},
            {"word":"Ellbogen", "meaning":"肘", "gender":"m"},
            {"word":"Hand", "meaning":"手", "gender":"f"},
            {"word":"Finger", "meaning":"指", "gender":"m"},
            {"word":"Nagel", "meaning":"爪", "gender":"m"},
            {"word":"Bein", "meaning":"脚", "gender":"n"},
            {"word":"Knie", "meaning":"膝", "gender":"n"},
            {"word":"Fuß", "meaning":"足", "gender":"m"},
            {"word":"Erkältung", "meaning":"風邪", "gender":"f"},
            {"word":"Grippe", "meaning":"インフルエンザ", "gender":"f"},
            {"word":"Knochen", "meaning":"骨", "gender":"m"},
            {"word":"Krankheit", "meaning":"病気", "gender":"f"},
            {"word":"Mediakament", "meaning":"薬", "gender":"n"},
            {"word":"Patient", "meaning":"患者", "gender":"m"},
            {"word":"Stuhlgang", "meaning":"便通", "gender":"m"},
            {"word":"Kopfschmerzen", "meaning":"頭痛", "gender":"p"}
        ],
        [
            {"word":"Geld", "meaning":"お金", "gender":"n"},
            {"word":"Körper", "meaning":"体, 物体", "gender":"m"},
            {"word":"Sinn", "meaning":"感覚, 意味", "gender":"m"},
            {"word":"Gefühl", "meaning":"感情", "gender":"n"}
        ]
    ],
    [
        [
            {"word":"Buchstabe", "meaning":"文字", "gender":"m"},
            {"word":"Heft", "meaning":"ノート", "gender":"n"},
            {"word":"Hefter", "meaning":"ホッチキス", "gender":"m"},
            {"word":"Klebstoff", "meaning":"のり", "gender":"m"},
            {"word":"Klebstreifen", "meaning":"セロハンテープ", "gender":"m"},
            {"word":"Kugelschreiber", "meaning":"ボールペン", "gender":"m"},
            {"word":"Lineal", "meaning":"定規", "gender":"n"},
            {"word":"Podium", "meaning":"教壇", "gender":"n"},
            {"word":"Radiergummi", "meaning":"消しゴム", "gender":"m"},
            {"word":"Tafel", "meaning":"黒板", "gender":"f"},
            {"word":"Tasche", "meaning":"鞄", "gender":"f"},
            {"word":"Text", "meaning":"テキスト", "gender":"m"},
            {"word":"Wörterbuch", "meaning":"辞典", "gender":"n"},
            {"word":"Abhandlung", "meaning":"論文", "gender":"f"},
            {"word":"Aufnahmeprüfung", "meaning":"入学試験", "gender":"f"},
            {"word":"Ausbildung", "meaning":"職業教育", "gender":"f"},
            {"word":"Bibliothek", "meaning":"図書館", "gender":"f"},
            {"word":"Bildung", "meaning":"教養", "gender":"f"},
            {"word":"Buch", "meaning":"本", "gender":"n"},
            {"word":"Fach", "meaning":"学科, 専門", "gender":"n"},
            {"word":"Ferien", "meaning":"休み", "gender":"p"},
            {"word":"Forschung", "meaning":"研究", "gender":"f"},
            {"word":"Frage", "meaning":"問題", "gender":"f"},
            {"word":"Grundschule", "meaning":"小学校", "gender":"f"},
            {"word":"Gymnasium", "meaning":"ギムナジウム", "gender":"n"},
            {"word":"Hauptschule", "meaning":"基幹学校", "gender":"f"},
            {"word":"Hausaufgabe", "meaning":"宿題", "gender":"f"},
            {"word":"Kindergarten", "meaning":"幼稚園", "gender":"m"},
            {"word":"Klasse", "meaning":"学年, クラス", "gender":"f"},
            {"word":"Klassenzimmer", "meaning":"教室", "gender":"n"},
            {"word":"Kommilitone", "meaning":"学友", "gender":"m"},
            {"word":"Lehrer", "meaning":"教師", "gender":"m"},
            {"word":"Note", "meaning":"成績", "gender":"f"},
            {"word":"Prüfung", "meaning":"試験", "gender":"f"},
            {"word":"Regel", "meaning":"規則", "gender":"f"},
            {"word":"Schule", "meaning":"学校", "gender":"f"},
            {"word":"Schulfest", "meaning":"文化祭", "gender":"n"},
            {"word":"Seite", "meaning":"ページ", "gender":"f"},
            {"word":"Sporthalle", "meaning":"体育館", "gender":"f"},
            {"word":"Sportplatz", "meaning":"グラウンド", "gender":"m"},
            {"word":"Student", "meaning":"学生", "gender":"m"},
            {"word":"Studium", "meaning":"学業", "gender":"n"},
            {"word":"Studenplan", "meaning":"時間割", "gender":"m"},
            {"word":"Thema", "meaning":"テーマ", "gender":"n"},
            {"word":"Universität", "meaning":"大学", "gender":"f"},
            {"word":"Unterricht", "meaning":"授業", "gender":"m"},
            {"word":"Verspätung", "meaning":"遅刻", "gender":"f"}
        ],
        [],
        [],
        [],
        [],
        []
    ],
    [],
    []
];}