function whole(){
    return [
    [],
    [],
    [
        [],
        [],
        [],
        [
            {"word":"Anzug", "meaning":"スーツ", "gender":"m"},
            {"word":"Bluse", "meaning":"ブラウス", "gender":"f"},
            {"word":"Hemd", "meaning":"シャツ", "gender":"n"},
            {"word":"Hose", "meaning":"ズボン", "gender":"f"},
            {"word":"Jacke", "meaning":"ジャケット", "gender":"f"},
            {"word":"Jeans", "meaning":"ジーンズ", "gender":"f"},
            {"word":"Kleid", "meaning":"ドレス", "gender":"n"},
            {"word":"Krawatte", "meaning":"ネクタイ", "gender":"f"},
            {"word":"Mantel", "meaning":"コート", "gender":"m"},
            {"word":"Pullover", "meaning":"セーター", "gender":"m"},
            {"word":"Regenmantel", "meaning":"レインコート", "gender":"m"},
            {"word":"Schlafanzug", "meaning":"パジャマ", "gender":"m"},
            {"word":"Schuh", "meaning":"靴", "gender":"m"},
            {"word":"Armbanduhr", "meaning":"腕時計", "gender":"f"},
            {"word":"Brille", "meaning":"眼鏡", "gender":"f"},
            {"word":"Diamant", "meaning":"ダイヤモンド", "gender":"m"},
            {"word":"Grütel", "meaning":"ベルト", "gender":"m"},
            {"word":"Halskette", "meaning":"ネックレス", "gender":"f"},
            {"word":"Handschuh", "meaning":"手袋", "gender":"m"},
            {"word":"Handtasche", "meaning":"ハンドバッグ", "gender":"f"},
            {"word":"Handtuch", "meaning":"ハンカチ", "gender":"n"},
            {"word":"Hut", "meaning":"帽子", "gender":"m"},
            {"word":"Lippenstift", "meaning":"口紅", "gender":"m"},
            {"word":"Ring", "meaning":"指輪", "gender":"m"},
            {"word":"Rock", "meaning":"スカート", "gender":"m"},
            {"word":"Schal", "meaning":"マフラー", "gender":"m"},
            {"word":"Sonnenbrille", "meaning":"サングラス", "gender":"f"},
            {"word":"Strumpf", "meaning":"ストッキング", "gender":"m"},
            {"word":"Ärmel", "meaning":"袖", "gender":"m"},
            {"word":"Halstuch", "meaning":"スカーフ", "gender":"n"},
            {"word":"Kleidung", "meaning":"(総称として) 服", "gender":"f"},
            {"word":"Mode", "meaning":"流行", "gender":"f"},
            {"word":"Schmuck", "meaning":"アクセサリー", "gender":"m"},
            {"word":"Unterwäsche", "meaning":"下着", "gender":"f"}
        ],
        [],
        [],
        [],
        []
    ],
    [],
    [],
    []
];}